//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arthropod
    {
        public string Animal { get; set; }
        public string HasFur { get; set; }
        public Nullable<int> Pop { get; set; }
        public string Dietry { get; set; }
        public int ArthropodsID { get; set; }
    }
}
