//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassfiedAsEndangered
    {
        public int Id { get; set; }
        public string AnimalName { get; set; }
        public string ClassifiedAs { get; set; }
        public string Population { get; set; }
        public string AnimalKingdom { get; set; }
    }
}
