//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;
    
    public partial class FoodType
    {

        public int Id { get; set; }
        
        [Display(Name = "Animal Name")]
        [Required]
        public string Animal_Name { get; set; }
        [Display(Name = "Foodtype Name")]
        [Required]
        public string FoodType1 { get; set; }
    }
}
